# Generated by Django 3.1.4 on 2020-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=100)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Style', models.CharField(max_length=100)),
                ('IBU', models.IntegerField(default=0)),
                ('Gravity', models.IntegerField(default=0)),
            ],
        ),
    ]
