# Generated by Django 3.1.4 on 2020-12-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bar',
            new_name='Beer',
        ),
    ]
