# Generated by Django 3.1.4 on 2021-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201223_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='Beer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
