# Generated by Django 3.1.4 on 2021-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_beer_beer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
